version: '3'
services:
  blog:
    image: blog:v1.0.2
    container_name: blog
    volumes:
      - ~/mydata/blog/images:/work/static/uploads/images
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8081:8081
    external_links:
      - mysql:mysql
      - redis:redis
      - minio:minio
  nginx:
    image: nginx:1.27.0
    container_name: nginx
    volumes:
      - ~/mydata/nginx/conf/conf.d:/etc/nginx/conf.d
      - ~/mydata/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ~/mydata/nginx/html:/etc/nginx/html
      - ~/mydata/nginx/dist:/etc/nginx/dist
      - ~/mydata/nginx/logs:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
    external_links:
      - minio:minio
      - blog:blog
