version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - ~/mydata/mysql/data:/var/lib/mysql #数据文件目录挂载
      - ~/mydata/mysql/log:/var/log/mysql #日志文件目录挂载
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  redis:
    image: redis:7.2
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ~/mydata/redis/data:/data #数据文件目录挂载
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6379:6379
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001" #指定数据目录及console运行端口启动
    volumes:
      - ~/mydata/minio/data:/data #数据目录挂载
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    ports:
      - 9000:9000
      - 9001:9001
